import type { ActionCardData } from "@/types/argus";
import type { BridgeRow } from "@/types/bridge";

export function makeActionCardData(overrides: Partial<ActionCardData> = {}): ActionCardData {
  return {
    symbol: "NVDA",
    verdict: "LONG",
    score: 0.62,
    high_conviction: false,
    entry: 100,
    stop: 95,
    target: 110,
    risk_reward: 2,
    long_votes: 40,
    short_votes: 10,
    wait_votes: 20,
    agreement_pct: 0.57,
    ret_1d: null,
    ret_5d: null,
    ret_20d: null,
    is_extended: false,
    entry_quality: "good",
    votes: [],
    agreed: [],
    dissented: [],
    notes: "",
    ...overrides,
  };
}

export function makeBridgeRow(overrides: Partial<BridgeRow> = {}): BridgeRow {
  return {
    ticker: "NVDA",
    fetch_symbol: "NVDA",
    setup_label: "",
    conviction: "med",
    quality_score: 0.6,
    cluster_overlap: 0,
    cluster_confirmed: false,
    cluster_bonus: 0,
    source_score: 0,
    mentions: 0,
    accounts: 0,
    catalysts: null,
    top_accounts: null,
    ret_1d: null,
    ret_5d: null,
    ret_20d: null,
    ret_126d: null,
    ret_252d: null,
    argus_verdict: "LONG",
    argus_score: 0.6,
    high_conviction: false,
    agreement_pct: 0.5,
    long_votes: 40,
    short_votes: 10,
    wait_votes: 20,
    entry: 100,
    stop: 95,
    target: 110,
    risk_reward: 2,
    is_extended: false,
    entry_quality: "clean",
    stop_anchor: "",
    sentiment_score: 0,
    tech_score: 0,
    combined_score: 0,
    catalyst_score: 0,
    vote_event_catalyst: 0,
    vote_earnings_proximity: 0,
    vote_squeeze_setup: 0,
    vote_growth_profitability: 0,
    vote_analyst_upside: 0,
    gate_flags: null,
    alignment: "ALIGNED",
    action_label: "",
    trade_style: "",
    combo: "",
    ticker_regime: "",
    n_eff: 0,
    group1: false,
    group2: false,
    near_aligned: false,
    report_group: null,
    theme: null,
    industry: null,
    next_earnings_date: null,
    earnings_in_days: null,
    extra: "",
    ...overrides,
  };
}
